spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  tokenHeader: Authorization
  secret: mySecret
#  是否设置token过期
  expired: true
#  过期时间，毫秒
  expiration: 600000
  head: "Bearer "
#  不需要token认证和跳过security认证的URI,支持*通配符，必须以 / 开头
  permitUris: "/register,/,/favicon.ico,/api/logManage/info/export,/download,/export,/api/product/exportAllDate,/produce/test,/testapi/**,/api/deviceOS/getDeviceOutputStatistics,/api/**,/export/**,/warehouseTest/**"

server:
  port: 8081

debug: true